/*
 * File: app/store/DeviceStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.store.DeviceStore', {
    extend: 'Ext.data.Store',

    requires: [
        'zvsMobile.model.Device',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.util.Grouper'
    ],

    config: {
        autoLoad: true,
        groupDir: 'DESC',
        model: 'zvsMobile.model.Device',
        storeId: 'DeviceStore',
        proxy: {
            type: 'odata',
            enablePagingParams: false,
            filterParam: '$filter',
            limitParam: '$top',
            noCache: false,
            sortParam: '$orderby',
            startParam: '$skip',
            url: 'http://10.1.0.54:50232/odata4/Devices/?$expand=Type&$filter=Type/UniqueIdentifier ne \'CONTROLLER\'',
            headers: {
                'Content-Type': 'application/json',
                'X-zvsToken': 'CC2D226814CBC713134BD9D09B892F10A9'
            },
            useDefaultXhrHeader: false,
            reader: {
                type: 'json',
                idProperty: 'Id',
                rootProperty: 'value'
            }
        },
        sorters: {
            property: 'Location'
        },
        grouper: {
            groupFn: function(item) {
                return item.get('Type');
            }
        }
    }
});