/*
 * File: app/store/DeviceValueTriggerStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.store.DeviceValueTriggerStore', {
    extend: 'Ext.data.Store',

    requires: [
        'zvsMobile.model.DeviceValueTrigger',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    config: {
        groupDir: 'DESC',
        model: 'zvsMobile.model.DeviceValueTrigger',
        storeId: 'DeviceValueTriggerStore',
        proxy: {
            type: 'ajax',
            enablePagingParams: false,
            filterParam: '$filter',
            limitParam: '$top',
            noCache: false,
            sortParam: '$orderby',
            startParam: '$skip',
            url: 'odata4/DeviceValueTriggers?$expand=StoredCommand',
            headers: {
                'Content-Type': 'application/json'
            },
            useDefaultXhrHeader: false,
            reader: {
                type: 'json',
                idProperty: 'Id',
                rootProperty: 'value'
            }
        }
    }
});