/*
 * File: app/controller/DeviceControl.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.controller.DeviceControl', {
    extend: 'Ext.app.Controller',

    statics: {
        createControl: function(command, defaultValue, commandType, device, component) {
            if(command.ArgumentType == 'LIST')
            {
                var options = [];
                command.Options.forEach(function(option){
                    options.push({text: option.Name,  value: option.Name});
                });

                if(defaultValue === null)
                {
                    defaultValue = '- select -';
                    options.unshift( {text: '- select -',  value: '- select -'});
                }

                var input = component.add({
                    xtype: 'selectfield',
                    label: command.Name,
                    value:defaultValue,
                    margin: '10 5 0 5 ',
                    command: command,
                    commandType: commandType,
                    device: device,
                    options: options
                });

                input.suspendEvents();
                input.setValue(defaultValue);
                input.resumeEvents(true);

            }
            else if(command.ArgumentType == 'NONE')
            {
                var input = component.add({
                    xtype: 'checkboxfield',
                    label: command.Name,

                    margin: '10 5 0 5 ',
                    command: command,
                    commandType: commandType,
                    device: device
                });
            }
            else if(command.ArgumentType == 'STRING')
            {

                var input = component.add({
                    xtype: 'textfield',
                    label: command.Name,
                    clearIcon:false,
                    margin: '10 5 0 5 ',
                    command: command,
                    commandType: commandType,
                    device: device
                });
                if(defaultValue !== null)
                {
                    input.suspendEvents();
                    input.setValue(defaultValue);
                    input.resumeEvents(true);
                }

            }
            else if(command.ArgumentType == 'BOOL')
            {

                var input = component.add({
                    xtype: 'togglefield',
                    label: command.Name,
                    margin: '10 5 0 5 ',
                    command: command,
                    commandType: commandType,
                    device: device
                });
                if(defaultValue !== null)
                {
                    input.suspendEvents();
                    input.setValue(defaultValue);
                    input.resumeEvents(true);
                }

            }
            else if(command.ArgumentType == 'BYTE' || command.ArgumentType == 'INTEGER' || command.ArgumentType == 'DECIMAL' || command.ArgumentType == 'SHORT')
            {

                var input = component.add({
                    xtype: 'numberfield',
                    label: command.Name,

                    clearIcon:false,
                    margin: '10 5 0 5 ',
                    command: command,
                    commandType: commandType,
                    device: device
                });
                if(defaultValue !== null)
                {
                    input.suspendEvents();
                    input.setValue(defaultValue);
                    input.resumeEvents(true);
                }

            }

        }
    },

    config: {
        control: {
            "panel#deviceControlPanel": {
                show: 'onControlPanelShow'
            },
            "devicecontrolpanel selectfield": {
                change: 'onSelectfieldChange'
            },
            "devicecontrolpanel textfield": {
                change: 'onTextfieldChange'
            },
            "devicecontrolpanel togglefield": {
                change: 'onToggleFieldChange'
            },
            "devicecontrolpanel checkboxfield": {
                change: 'checkboxfieldChange'
            }
        }
    },

    onControlPanelShow: function(component, eOpts) {
        if(component.IsLoaded)
            return;

        component.IsLoaded = true;

        var deviceRecord = component.getParent().getRecord();
        component.setRecord(deviceRecord);
        var device = deviceRecord.getData();

        //Create Device Type Commands
        var typeStore = Ext.getStore('DeviceTypeCommandStore');
        var uri = 'odata4/DeviceTypeCommands/?$filter=DeviceTypeId eq ' + device.DeviceTypeId;
        uri = uri + '&$expand=Options';
        typeStore.getProxy().setUrl(uri);
        typeStore.load({
            callback: function(records, operation, success) {
                // the operation object contains all of the details of the load operation

                typeStore.getData().each(function(item){
                    var command = item.raw;
                    zvsMobile.controller.DeviceControl.createControl(command, null, 'DeviceTypeCommand', device, component);
                });
            }
        });

        //Create Device Commands
        Ext.Ajax.request({
            url: 'odata4/DeviceValues/?$filter=DeviceId eq '+device.Id+' and Genre eq \'User\'&$select=UniqueIdentifier, Value',
            method: 'GET',
            scope : this,
            headers: {
                'Content-Type': 'application/json',
                'X-zvsToken': zvsMobile.app.getToken()
            },
            success: function (response, opts) {

                if (response.status === 200) {

                    var result = JSON.parse(response.responseText);

                    if(result.value.length === 0)
                        return;

                    var values = result.value;

                    var commandFilter = '';

                    for(i=0; i<values.length; i++) {
                        var value = values[i];

                        if(i !== 0 )
                            commandFilter = commandFilter + ' or';

                        commandFilter = commandFilter + ' CustomData2 eq \''+value.UniqueIdentifier+'\'';
                    }

                    var uri = 'odata4/DeviceCommands/?$filter=DeviceId eq ' + device.Id;
                    uri = uri + ' and ' + commandFilter;
                    uri = uri + '&$expand=Options';

                    var store = Ext.getStore('DeviceCommandStore');
                    store.getProxy().setUrl(uri);
                    store.load({
                        callback: function(records, operation, success) {
                            // the operation object contains all of the details of the load operation

                            store.getData().each(function(item){

                                var defaultValue= null;
                                for(i=0; i<values.length; i++) {
                                    if(values[i].UniqueIdentifier == item.data.CustomData2)
                                        defaultValue =values[i].Value;
                                }

                                var command = item.raw;
                                zvsMobile.controller.DeviceControl.createControl(command, defaultValue, 'DeviceCommand', device, component);

                            });
                        },
                        scope: this
                    });
                }
                else {
                    Ext.Msg.alert('Error',  'Unabled to load device commands.');
                }
            },
            failure: function (response, opts) {
                var result = JSON.parse(response.responseText);
                Ext.Msg.alert('Error',  result.error.message);
            }
        });

    },

    onSelectfieldChange: function(selectfield, newValue, oldValue, eOpts) {
        if(newValue === '- select -')
            return;

        var type = selectfield.getInitialConfig().commandType;
        var id = selectfield.getInitialConfig().command.Id;
        var device = selectfield.getInitialConfig().device;

        if(type === 'DeviceCommand' || type === 'DeviceTypeCommand')
        {
            selectfield.disable();
            zvsMobile.app.executeCommand(id, newValue.toString(), device.Id.toString(), function(success, error){
                selectfield.enable();
                if(success)
                {
                    Ext.Msg.alert('Success',  success);

                    var deviceStore = Ext.getStore('DeviceStore');
                    deviceStore.needsRefresh = true;
                }
                else
                     Ext.Msg.alert('Error',  error);
            });
        }


    },

    onTextfieldChange: function(textfield, newValue, oldValue, eOpts) {
        if(textfield.command)
        {

            var type = textfield.commandType;
            var command = textfield.getInitialConfig().command;
            var id = textfield.getInitialConfig().command.Id;
            var device = textfield.getInitialConfig().device;

            if(type === 'DeviceCommand' || type === 'DeviceTypeCommand')
            {
                if(command.ArgumentType == 'STRING')
                {
                    textfield.disable();
                    zvsMobile.app.executeCommand(id, newValue.toString(), device.Id.toString(), function(success, error){
                        textfield.enable();
                        if(success)
                        {
                            Ext.Msg.alert('Success',  success);

                            var deviceStore = Ext.getStore('DeviceStore');
                            deviceStore.needsRefresh = true;
                        }
                        else
                            textfield.getParent().setError(error);
                    });
                }
                else if(command.ArgumentType == 'BYTE' || command.ArgumentType == 'INTEGER' || command.ArgumentType == 'DECIMAL' || command.ArgumentType == 'SHORT')
                {
                    var intRegex = /^\d+$/;
                    if(newValue === '' ||
                       ((newValue < 0 || newValue >255) && command.ArgumentType == 'BYTE')
                       //|| (item.data.ArgumentType == 'INTEGER' && intRegex.test(someNumber))
                      )
                    {
                        Ext.Msg.alert('Aw, Snap!', 'Input not valid.');
                        textfield.suspendEvents();
                        textfield.setValue(oldValue);
                        textfield.resumeEvents(true);
                        return;
                    }


                    textfield.disable();
                    zvsMobile.app.executeCommand(id, newValue.toString(), device.Id.toString(), function(success, error){
                        textfield.enable();
                        if(success)
                            {
                            textfield.getParent().setSuccess(success);

                                var deviceStore = Ext.getStore('DeviceStore');
                    deviceStore.needsRefresh = true;
                            }
                        else
                            Ext.Msg.alert('Error',  error);
                    });

                }
            }
        }
    },

    onToggleFieldChange: function(togglefield, newValue, oldValue, eOpts) {
        var type = togglefield.getInitialConfig().commandType;
        var id = togglefield.getInitialConfig().command.Id;
        var device = togglefield.getInitialConfig().device;

        if(type === 'DeviceCommand' || type === 'DeviceTypeCommand')
        {
            togglefield.disable();
            zvsMobile.app.executeCommand(id, newValue> 0 ? 'true':'false', device.Id.toString(), function(success, error){
                togglefield.enable();
                if(success){
                    Ext.Msg.alert('Success',  success);
                    var deviceStore = Ext.getStore('DeviceStore');
                    deviceStore.needsRefresh = true;
                }
                else
                    Ext.Msg.alert('Error',  error);
            });
        }


    },

    checkboxfieldChange: function(checkboxfield, newValue, oldValue, eOpts) {
        var type = checkboxfield.getInitialConfig().commandType;
        var id = checkboxfield.getInitialConfig().command.Id;
        var device = checkboxfield.getInitialConfig().device;

        if(type === 'DeviceCommand' || type === 'DeviceTypeCommand')
        {
            //checkboxfield.disable();
            zvsMobile.app.executeCommand(id, newValue.toString(), device.Id.toString(), function(success, error){
                //checkboxfield.enable();
                if(success)
                {
                    checkboxfield.getParent().setSuccess(success);
                    var deviceStore = Ext.getStore('DeviceStore');
                    deviceStore.needsRefresh = true;
                }
                else
                    Ext.Msg.alert('Error',  error);
            });


            checkboxfield.suspendEvents();
            setTimeout(function(){checkboxfield.uncheck();
                                  checkboxfield.resumeEvents(true);}, 900);

        }
    }

});