/*
 * File: app/controller/DeviceValueHistory.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.controller.DeviceValueHistory', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            mainView: 'navigationview#mainView'
        },

        control: {
            "list#mylist": {
                itemtap: 'onListItemTap'
            }
        }
    },

    onListItemTap: function(dataview, index, target, record, e, eOpts) {


        var deviceValue = record.getData();

        if(deviceValue.ValueType == 'INTEGER' ||
           deviceValue.ValueType == 'DECIMAL' ||
           deviceValue.ValueType == 'BYTE')
        {
            var store = Ext.getStore('DeviceValueHistoryStore');
            var uri = 'odata4/DeviceValueHistories/?$filter=DeviceValueId eq ' + record.data.Id;
            store.getProxy().setUrl(uri);
            store.load();

            this.getMainView().push({
                xtype: 'devicevaluenumberhistorychart',
                title: deviceValue.Name + ' - History'
            });
        }
    }

});