/*
 * File: app/controller/GroupEdit.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.controller.GroupEdit', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            mainView: 'navigationview#mainView'
        },

        control: {
            "formpanel#groupEdit": {
                show: 'onFormpanelShow'
            },
            "button#saveGroupButton": {
                tap: 'onSaveButtonTap'
            }
        }
    },

    onFormpanelShow: function(component, eOpts) {
        var deviceRecord = component.getParent().getRecord();
        component.setRecord(deviceRecord);
    },

    onSaveButtonTap: function(button, e, eOpts) {
        var editPanel = button.getParent();
        var groupRecord = editPanel.getRecord();
        button.disable();

        Ext.Ajax.request({
            url: 'odata4/Groups('+groupRecord.getData().Id+')/',
            method: 'PATCH',
            scope : this,
            jsonData: {
                Name: editPanel.getValues().Name
            },
            headers: {
                'Content-Type': 'application/json',
                'X-zvsToken': zvsMobile.app.getToken()
            },
            success: function (response, opts) {

                Ext.Msg.alert('Done',  'Group updated');
                var groupStore = Ext.getStore('GroupStore');
                var record = groupStore.getById(groupRecord.getData().Id);
                record.set(editPanel.getValues());
                var mainView = this.getMainView();
                mainView.getNavigationBar().setTitle(record.data.Name);

                button.enable();

            },
            failure: function (response, opts) {
                Ext.Msg.alert('Error',  'Group update failed. ' + response.responseText);
                button.enable();
            }
        });
    }

});