/*
 * File: app/controller/Scenes.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.controller.Scenes', {
    extend: 'Ext.app.Controller',
    alias: 'controller.scenespanel',

    config: {
        control: {
            "panel#scenesPanel": {
                initialize: 'onPanelInitialize'
            }
        }
    },

    onPanelInitialize: function(component, eOpts) {
        var sceneStore = Ext.getStore('SceneStore');
        sceneStore.load();
    }

});