/*
 * File: app/controller/Trigger.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.controller.Trigger', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            mainView: 'navigationview#mainView'
        },

        control: {
            "panel#triggerPanel": {
                initialize: 'onPanelInitialize'
            },
            "button#refreshTriggerBtn": {
                tap: 'onRefreshButtonTap'
            },
            "searchfield#triggerSearchfield": {
                keyup: 'onSearchfieldKeyup',
                clearicontap: 'onSearchfieldClearicontap'
            },
            "dataview#triggerDataview": {
                itemtap: 'onDataviewItemTap'
            }
        }
    },

    onPanelInitialize: function(component, eOpts) {
        var store = Ext.getStore('DeviceValueTriggerStore');
        store.clearFilter();
        store.load();
    },

    onRefreshButtonTap: function(button, e, eOpts) {
        var store = Ext.getStore('DeviceValueTriggerStore');
        store.load();
    },

    onSearchfieldKeyup: function(textfield, e, eOpts) {
        queryString = textfield.getValue();

        var store = Ext.getStore('DeviceValueTriggerStore');
        store.clearFilter();

        if(queryString) {
            var thisRegEx = new RegExp(queryString, "i");
            store.filterBy(function(record) {
                if (thisRegEx.test(record.get('Name')))
                    return true;
                return false;
            });
        }
    },

    onSearchfieldClearicontap: function(textfield, e, eOpts) {
        var store = Ext.getStore('DeviceValueTriggerStore');
        store.clearFilter();
    },

    onDataviewItemTap: function(dataview, index, target, record, e, eOpts) {
        var mainView = this.getMainView();
        var triggerRecord = record;

        mainView.push({
            xtype: 'triggerdetailspanel',
            title: triggerRecord.data.Name,
            record: triggerRecord
        });
    }

});