/*
 * File: app/model/BuiltinCommand.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.model.BuiltinCommand', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field',
        'Ext.data.association.HasMany'
    ],
    uses: [
        'zvsMobile.model.CommandOption'
    ],

    config: {
        idProperty: 'Id',
        fields: [
            {
                name: 'Id',
                type: 'int'
            },
            {
                name: 'Name',
                type: 'string'
            },
            {
                name: 'UniqueIdentifier',
                type: 'string'
            },
            {
                name: 'Value',
                type: 'string'
            },
            {
                name: 'ArgumentType',
                type: 'string'
            },
            {
                name: 'Description',
                type: 'string'
            },
            {
                name: 'CustomData1',
                type: 'string'
            },
            {
                name: 'CustomData2',
                type: 'string'
            },
            {
                name: 'SortOrder',
                type: 'int'
            },
            {
                name: 'Help',
                type: 'string'
            }
        ],
        hasMany: {
            associationKey: 'Options',
            primaryKey: 'Id',
            model: 'zvsMobile.model.CommandOption',
            foreignKey: 'CommandId',
            name: 'opts'
        }
    }
});