/*
 * File: app/model/DeviceValueHistory.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.model.DeviceValueHistory', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        idProperty: 'Id',
        fields: [
            {
                name: 'Id',
                type: 'int'
            },
            {
                name: 'DateTime',
                type: 'date'
            },
            {
                name: 'DeviceValueId',
                type: 'int'
            },
            {
                name: 'Value',
                type: 'string'
            }
        ]
    }
});