/*
 * File: app/model/LogItem.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.model.LogItem', {
    extend: 'Ext.data.Model',
    alias: 'model.logitem',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        idProperty: 'Id',
        fields: [
            {
                name: 'Datetime',
                type: 'string'
            },
            {
                name: 'Message',
                type: 'string'
            },
            {
                name: 'Source',
                type: 'string'
            },
            {
                name: 'Level',
                type: 'string'
            },
            {
                name: 'Id',
                type: 'int'
            }
        ]
    }
});