/*
 * File: app/model/Settings.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.model.Settings', {
    extend: 'Ext.data.Model',
    alias: 'model.settings',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        idProperty: 'Id',
        fields: [
            {
                name: 'Id',
                type: 'int'
            },
            {
                name: 'Url',
                type: 'string'
            },
            {
                name: 'Port',
                type: 'int'
            },
            {
                name: 'Token',
                type: 'string'
            }
        ],
        validations: [
            {
                type: 'format',
                field: 'Port',
                matcher: /^0*(?:6553[0-5]|655[0-2][0-9]|65[0-4][0-9]{2}|6[0-4][0-9]{3}|[1-5][0-9]{4}|[1-9][0-9]{1,3}|[0-9])$/,
                message: 'Invalid'
            },
            {
                type: 'presence',
                field: 'Token'
            },
            {
                type: 'presence',
                field: 'Port'
            },
            {
                type: 'presence',
                field: 'Url'
            }
        ]
    }
});