/*
 * File: app/model/StoredCommand.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.model.StoredCommand', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field',
        'Ext.data.association.HasOne',
        'Ext.data.association.HasMany'
    ],
    uses: [
        'zvsMobile.model.SceneCommand',
        'zvsMobile.model.DeviceValueTrigger'
    ],

    config: {
        idProperty: 'Id',
        fields: [
            {
                name: 'Id',
                type: 'int'
            },
            {
                name: 'CommandId',
                type: 'int'
            },
            {
                name: 'Argument',
                type: 'string'
            },
            {
                name: 'Argument2',
                type: 'string'
            },
            {
                name: 'TargetObjectName',
                type: 'string'
            },
            {
                name: 'Description',
                type: 'string'
            }
        ],
        hasOne: {
            associatedName: 'SceneCommand',
            associationKey: 'SceneCommand',
            primaryKey: 'Id',
            model: 'zvsMobile.model.SceneCommand',
            foreignKey: 'CommandId'
        },
        hasMany: {
            associatedName: 'DeviceValueTrigger',
            associationKey: 'DeviceValueTrigger',
            primaryKey: 'Id',
            model: 'zvsMobile.model.DeviceValueTrigger'
        }
    }
});