/*
 * File: app/view/DeviceDetailsTabPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.view.DeviceDetailsTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.devicedetailstabpanel',

    requires: [
        'zvsMobile.view.SwitchControlPanel',
        'zvsMobile.view.DimmerControlPanel',
        'zvsMobile.view.ThermoControlPanel',
        'zvsMobile.view.DeviceValuesPanel',
        'Ext.Panel',
        'Ext.tab.Bar'
    ],

    config: {
        activeItem: 3,
        id: 'deviceDetailsTabPanel',
        items: [
            {
                xtype: 'switchcontrolpanel',
                title: 'Control',
                iconCls: 'action'
            },
            {
                xtype: 'dimmercontrolpanel',
                title: 'Control',
                iconCls: 'action'
            },
            {
                xtype: 'thermocontrolpanel',
                title: 'Control',
                iconCls: 'action'
            },
            {
                xtype: 'devicevaluespanel',
                title: 'Values',
                iconCls: 'more'
            }
        ],
        tabBar: {
            docked: 'bottom',
            ui: 'neutral',
            layout: {
                type: 'hbox',
                pack: 'center'
            }
        }
    }

});