/*
 * File: app/view/DeviceControlPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.view.DeviceControlPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.devicecontrolpanel',

    requires: [
        'Ext.field.Text',
        'Ext.Toolbar',
        'Ext.field.Toggle',
        'Ext.field.Select'
    ],

    config: {
        itemId: 'deviceControlPanel',
        scrollable: 'vertical',
        items: [
            {
                xtype: 'textfield',
                disabled: true,
                itemId: 'locationTextField',
                margin: '10 5 0 5 ',
                label: 'Room'
            },
            {
                xtype: 'textfield',
                disabled: true,
                itemId: 'typeTextField',
                margin: '10 5 0 5 ',
                label: 'Type'
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                itemId: 'feedbackLabel',
                padding: '10px',
                scrollable: 'vertical'
            }
        ]
    },

    setError: function(message) {
        var feedbackLabel= this.down('#feedbackLabel');
        feedbackLabel.setHtml(message);
        feedbackLabel.setStyle('color:red');
        setTimeout(function(){ feedbackLabel.setHtml('');}, 5000);
    },

    setSuccess: function(message) {
        var feedbackLabel= this.down('#feedbackLabel');
        feedbackLabel.setHtml(message);
        feedbackLabel.setStyle('color:green');
        setTimeout(function(){ feedbackLabel.setHtml('');}, 5000);
    }

});