/*
 * File: app/view/DeviceEdit.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.view.DeviceEdit', {
    extend: 'Ext.form.Panel',
    alias: 'widget.deviceedit',

    requires: [
        'Ext.Spacer',
        'Ext.form.FieldSet',
        'Ext.field.Text',
        'Ext.Button'
    ],

    config: {
        itemId: 'deviceEdit',
        items: [
            {
                xtype: 'spacer',
                height: '10px'
            },
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'textfield',
                        itemId: 'deviceNameField',
                        label: 'Name',
                        name: 'Name',
                        required: true
                    },
                    {
                        xtype: 'textfield',
                        itemId: 'deviceLocationField',
                        label: 'Location',
                        name: 'Location',
                        required: true
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'saveDeviceButton',
                margin: 10,
                ui: 'action',
                text: 'Save'
            }
        ]
    }

});