/*
 * File: app/view/GroupsPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.view.GroupsPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.groupspanel',

    requires: [
        'Ext.dataview.DataView',
        'Ext.XTemplate',
        'Ext.Toolbar',
        'Ext.field.Search',
        'Ext.Spacer',
        'Ext.Button'
    ],

    config: {
        itemId: 'groupsPanel',
        layout: 'fit',
        items: [
            {
                xtype: 'dataview',
                cls: 'dataview-inline',
                itemId: 'groupsDataview',
                style: '',
                inline: true,
                itemCls: 'groupItem',
                itemTpl: [
                    '<div class="group-item">',
                    '	<h4 class="group-name-truncate">{Name}</h4>  ',
                    '    <i class="GROUP group-icon"></i>   	    ',
                    '</div>'
                ],
                store: 'GroupStore'
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'searchfield',
                        itemId: 'groupSearchfield',
                        width: '275px',
                        label: 'Search'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        itemId: 'refreshGroupsBtn',
                        iconCls: 'refresh'
                    }
                ]
            }
        ]
    }

});