/*
 * File: app/view/HomePanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.view.HomePanel', {
    extend: 'Ext.Panel',
    alias: 'widget.homepanel',

    requires: [
        'Ext.dataview.DataView',
        'Ext.XTemplate'
    ],

    config: {
        baseCls: 'x-panel tileParent',
        itemId: 'homePanel',
        autoDestroy: false,
        layout: 'fit',
        scrollable: 'vertical',
        items: [
            {
                xtype: 'dataview',
                cls: 'dataview-inline',
                data: [
                    {
                        Name: 'Devices',
                        Color: '#2CAFE7',
                        Iconcls: 'DIMMER',
                        navView: 'devicespanel'
                    },
                    {
                        Name: 'Scenes',
                        Color: '#9EC974',
                        Iconcls: 'SCENE',
                        navView: 'scenespanel'
                    },
                    {
                        Name: 'Groups',
                        Color: '#F5A70E',
                        Iconcls: 'GROUP',
                        navView: 'groupspanel'
                    },
                    {
                        Name: 'Scheduled Tasks',
                        Color: '#FD605C',
                        Iconcls: 'st-icon',
                        navView: 'scheduledtaskspanel'
                    },
                    {
                        Name: 'Triggers',
                        Color: '#B173C9',
                        Iconcls: 'triggers-icon',
                        navView: 'triggerpanel'
                    },
                    {
                        Name: 'Log',
                        Color: '#CACED1',
                        Iconcls: 'log-icon',
                        navView: 'loglist'
                    },
                    {
                        Name: 'Settings',
                        Color: '#EE5445',
                        Iconcls: 'setting-icon',
                        navView: 'settingsform'
                    }
                ],
                itemId: 'homeDataview',
                style: '',
                inline: true,
                itemTpl: [
                    '<div class="home-tile" style="background-color:{Color}">	  ',
                    '    <i class="{Iconcls} home-icon"></i> ',
                    '    <h4 class="home-name-truncate">{Name}</h4>',
                    '</div>'
                ]
            }
        ]
    }

});