/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.view.MainView', {
    extend: 'Ext.navigation.View',
    alias: 'widget.mainview',

    requires: [
        'zvsMobile.view.HomePanel',
        'Ext.Panel',
        'Ext.navigation.Bar',
        'Ext.Button'
    ],

    config: {
        itemId: 'mainView',
        autoDestroy: false,
        items: [
            {
                xtype: 'homepanel',
                title: 'zVirtualScenes Mobile'
            }
        ],
        navigationBar: {
            docked: 'top',
            itemId: 'navBar',
            ui: 'light',
            autoDestroy: false,
            items: [
                {
                    xtype: 'button',
                    itemId: 'menuButton',
                    iconCls: 'list',
                    text: ''
                }
            ]
        }
    }

});