/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.view.MainView', {
    extend: 'Ext.navigation.View',
    alias: 'widget.mainview',

    requires: [
        'zvsMobile.view.DevicesPanel',
        'Ext.Panel',
        'Ext.navigation.Bar',
        'Ext.Button'
    ],

    config: {
        itemId: 'mainView',
        items: [
            {
                xtype: 'devicespanel',
                title: 'Devices'
            }
        ],
        navigationBar: {
            centered: false,
            docked: 'top',
            itemId: 'navBar',
            ui: 'nuetral',
            layout: {
                type: 'hbox',
                align: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    itemId: 'menuButton',
                    iconCls: 'more',
                    text: ''
                },
                {
                    xtype: 'button',
                    align: 'right',
                    itemId: 'settingsButton',
                    iconCls: 'settings',
                    text: ''
                }
            ]
        }
    }

});