/*
 * File: app/view/NavMenu.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.view.NavMenu', {
    extend: 'Ext.Panel',
    alias: 'widget.navmenu',

    requires: [
        'Ext.Button'
    ],

    config: {
        centered: true,
        hidden: true,
        itemId: 'navMenu',
        padding: 20,
        hideOnMaskTap: true,
        modal: true,
        items: [
            {
                xtype: 'button',
                navView: 'devicespanel',
                itemId: 'DevicesBtn',
                margin: '20 3 3 3',
                iconCls: 'light',
                text: 'Devices'
            },
            {
                xtype: 'button',
                navView: 'scenespanel',
                itemId: 'ScenesBtn',
                margin: 3,
                style: 'color:#9EC974',
                iconCls: 'scene',
                text: 'Scenes'
            },
            {
                xtype: 'button',
                navView: 'groupspanel',
                itemId: 'GroupsBtn',
                margin: 3,
                iconCls: 'group',
                text: 'Groups'
            },
            {
                xtype: 'button',
                navView: 'scheduledtaskspanel',
                itemId: 'TaskBtn',
                margin: 3,
                iconCls: 'task',
                text: 'Tasks'
            },
            {
                xtype: 'button',
                navView: 'triggerdetailspanel',
                itemId: 'TriggersBtn',
                margin: 3,
                iconCls: 'trigger',
                text: 'Triggers'
            },
            {
                xtype: 'button',
                navView: 'loglist',
                margin: 3,
                iconCls: 'log',
                text: 'Log'
            },
            {
                xtype: 'button',
                navView: 'settingsform',
                itemId: 'SettingsBtn',
                margin: '20 3 3 3',
                iconCls: 'settings3',
                text: 'Settings'
            }
        ]
    }

});