/*
 * File: app/view/SceneControlPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.view.SceneControlPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.scenecontrolpanel',

    requires: [
        'Ext.Button',
        'Ext.XTemplate'
    ],

    config: {
        itemId: 'sceneControlPanel',
        scrollable: 'vertical',
        tpl: [
            '',
            '<table class="info-table">',
            '    <thead>',
            '        <tr>',
            '            <th>Order</th>',
            '            <th >Command</th>',
            '        </tr>',
            '    </thead>',
            '    <tbody>',
            '        <tpl for=".">',
            '            <tr>                    ',
            '                <td>{SortOrder}</td>',
            '                <td>{TargetObjectName} {Description}</td>',
            '            </tr>',
            '        </tpl>',
            '    </tbody>',
            '</table>',
            ''
        ],
        items: [
            {
                xtype: 'button',
                itemId: 'activateSceneBtn',
                margin: 10,
                text: 'Activate Scene'
            }
        ]
    }

});