/*
 * File: app/view/SceneTabPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.view.SceneTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.scenetabpanel',

    requires: [
        'zvsMobile.view.SceneControlPanel',
        'zvsMobile.view.SceneEdit',
        'Ext.form.Panel',
        'Ext.tab.Bar'
    ],

    config: {
        itemId: 'scenetabpanel',
        items: [
            {
                xtype: 'scenecontrolpanel',
                title: 'Control',
                iconCls: 'action'
            },
            {
                xtype: 'sceneedit',
                title: 'Edit',
                iconCls: 'compose'
            }
        ],
        tabBar: {
            docked: 'bottom'
        }
    }

});