/*
 * File: app/view/ScheduledTasksPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.view.ScheduledTasksPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.scheduledtaskspanel',

    requires: [
        'Ext.dataview.DataView',
        'Ext.XTemplate',
        'Ext.Toolbar',
        'Ext.field.Search',
        'Ext.Spacer',
        'Ext.Button'
    ],

    config: {
        itemId: 'scheduledTasksPanel',
        layout: 'fit',
        items: [
            {
                xtype: 'dataview',
                cls: 'dataview-inline',
                itemId: 'scheduledTasksDataview',
                style: '',
                inline: true,
                itemCls: 'stItem',
                itemTpl: [
                    '<div class="st-item">',
                    '    <h4 class="st-name-truncate">{Name}</h4>  ',
                    '    <i class="st-icon st-box-icon"></i> ',
                    '    <div class="st-status">{Description}</div>	    ',
                    '</div>'
                ],
                store: 'ScheduledTasksStore'
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'searchfield',
                        itemId: 'taskSearchfield',
                        width: '275px',
                        label: 'Search'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        itemId: 'refreshScheduledTasksBtn',
                        iconCls: 'refresh'
                    }
                ]
            }
        ]
    }

});