/*
 * File: app/view/ScheduledTasksDetailsTabPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.view.ScheduledTasksDetailsTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.taskpanel',

    requires: [
        'zvsMobile.view.ScheduledTaskEdit',
        'Ext.tab.Bar',
        'Ext.form.Panel'
    ],

    config: {
        itemId: 'scheduledTasksDetailsTabPanel',
        tabBar: {
            docked: 'bottom',
            itemId: 'actionTabBar',
            ui: 'neutral',
            layout: {
                type: 'hbox',
                pack: 'center'
            }
        },
        items: [
            {
                xtype: 'scheduledtaskedit',
                title: 'Edit',
                iconCls: 'compose'
            }
        ]
    }

});