/*
 * File: app/view/SettingsForm.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.view.SettingsForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.settingsform',

    requires: [
        'Ext.Spacer',
        'Ext.form.FieldSet',
        'Ext.field.Url',
        'Ext.field.Number',
        'Ext.Button',
        'Ext.MessageBox'
    ],

    config: {
        itemId: 'settingsForm',
        items: [
            {
                xtype: 'spacer',
                height: '10px'
            },
            {
                xtype: 'fieldset',
                itemId: 'settingFieldSet',
                items: [
                    {
                        xtype: 'urlfield',
                        itemId: 'myurlfield',
                        label: 'Url',
                        name: 'Url',
                        required: true
                    },
                    {
                        xtype: 'numberfield',
                        itemId: 'mynumberfield',
                        label: 'Port',
                        name: 'Port',
                        required: true,
                        maxValue: 65535,
                        minValue: 1,
                        stepValue: 1
                    },
                    {
                        xtype: 'textfield',
                        itemId: 'tokenTextField',
                        label: 'Token',
                        name: 'Token',
                        required: true
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'saveSettingsButton',
                margin: 10,
                ui: 'action',
                text: 'Save'
            }
        ]
    }

});