/*
 * File: app/view/TriggerEdit.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('zvsMobile.view.TriggerEdit', {
    extend: 'Ext.form.Panel',
    alias: 'widget.triggeredit',

    requires: [
        'Ext.Spacer',
        'Ext.form.FieldSet',
        'Ext.field.Text',
        'Ext.field.Checkbox',
        'Ext.Label',
        'Ext.XTemplate',
        'Ext.Button'
    ],

    config: {
        itemId: 'triggerEdit',
        items: [
            {
                xtype: 'spacer',
                height: '10px'
            },
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Name',
                        name: 'Name',
                        required: true
                    },
                    {
                        xtype: 'checkboxfield',
                        label: 'Enabled',
                        name: 'IsEnabled'
                    }
                ]
            },
            {
                xtype: 'spacer',
                height: '10px'
            },
            {
                xtype: 'label',
                itemId: 'commandLabel',
                margin: '15 15',
                style: 'font-size:1.1em',
                tpl: [
                    'When {TriggerDescription} then {Description} {TargetObjectName}'
                ]
            },
            {
                xtype: 'button',
                itemId: 'saveTriggerButton',
                margin: 10,
                ui: 'action',
                text: 'Save'
            }
        ]
    }

});