/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'Device',
        'DeviceValue',
        'Settings',
        'Scene',
        'Group',
        'DeviceCommandOption',
        'DeviceCommand'
    ],
    stores: [
        'DeviceStore',
        'DeviceValuesStore',
        'Settings',
        'SceneStore',
        'GroupStore',
        'DeviceCommandStore'
    ],
    views: [
        'MainView',
        'DevicesPanel',
        'NavMenu',
        'DeviceValuesPanel',
        'DeviceDetailsTabPanel',
        null,
        null,
        'DeviceControlPanel',
        'SettingsForm',
        'ScenesPanel',
        'GroupsPanel',
        'HomePanel'
    ],
    controllers: [
        'Navigation',
        'Devices',
        'Settings',
        'Scenes',
        'Group'
    ],
    name: 'zvsMobile',

    getToken: function() {
        var store = Ext.getStore('Settings');
        var setting = store.getById(1);
        if(setting && setting.data && setting.data.Token)
        return setting.data.Token;

        return 'defaultToken';


    },

    getBaseUrl: function() {
        var settingsStore = Ext.getStore('Settings');
        var record = settingsStore.getById(1);

        if(record && record.data && record.data.Url&& record.data.Port)
            return record.data.Url + ':'+ record.data.Port +'/' ;

            return 'http://localhost:8080/';
    },

    launch: function() {

        Ext.create('zvsMobile.view.MainView', {fullscreen: true});
    }

});
